a,b=input("Enter 2 nums:").split(" ",2)
print("*****BitWise********")
print("AND={}".format(int(a)&int(b)))
print("OR=",int(a)|int(b))
print("XOR=",int(a)^int(b))
print("a>>1=",int(a)>>1)
print("b<<1=",int(b)<<1)
print("~a=",~int(a))
print("******Operation******")
print("a+b=",int(a)+int(b))
print("a-b=",int(a)-int(b))
print("a*b=",int(a)*int(b))
print("a/b=",int(a)/int(b))
print("a**b=",int(a)**int(b))
print("a//b=",int(a)//int(b))

